Ganodorf/edrania-plugin

- js/edrania.js
- js/hoverInfo.js
- manifest.json
Made info hover boxes less buggy by canceling the entire event when user leaves link.
Added display of a players highest damage to player hover.
> Hover info update

- js/challenges.js
- js/edrania.js
- js/hoverInfo.js
- js/teamGame.js
- manifest.json
Fix for latest update pölus remove prefill from create team game.
> Version 1.2.1

- js/edrania.js
- js/workDistrict.js
- manifest.json
Display earned salary next to each shift option.
> [feat] Work district: append salary to each shift

- js/hoverInfo.js
- js/teamGame.js
Hover for team in team game that display the highest damage in the team.
Display different colors for players health in team games.
> Team hover

- js/workshop.js
If more than remaining rounds, that is.
> [fix] Workshop: allow working all available rounds

- js/teamGame.js
Haven't really been able to test this, yet. But by the pure looks of it, it looks legit to me.
> [fix] Team game: send one ready request at a time

- js/edrania.js
- js/hoverInfo.js
- js/talentCalculator.js
- js/tavern.js
- js/teamGame.js
- js/workDistrict.js
- js/workshop.js
- Explicitly parse integers with base/radix 10
> [fix] Hover info team game: compare hardest hit as integers

- js/duelReport.js
- js/edrania.js
- js/profile.js
- js/teamGame.js
- manifest.json
Add a **Rematch**-button to 1-on-1 gladiator duel reports the player is part of. Uses default tactics.
Depends on https://github.com/Ganodorf/edrania-plugin/pull/36, so I would merge that first.
> [feat] Duel report: add rematch button

- js/edrania.js
- js/tavern.js
- js/vendor.js
Simply refresh status instead.
> [fix] Vendor: don't reload page after quick purchase

- js/teamGame.js
Team count becomes out-of-sync every now and then. If so, fix it.
> [fix] Team game: ensure team count is up-to-date

- css/edrania.css
Make numeric characters equal width.
> [style] Team game: align chat timestamps

- js/playerStatus.js
- Status label
- Charge count until full health
- Timestamp at full health
**Demo**
https://user-images.githubusercontent.com/516549/113493717-479e2b80-94e2-11eb-9ec2-6bd2a704fe17.mov
> [feat] Player status: health status tooltip

- js/challenge.js
- js/duelReport.js
- js/edrania.js
- js/profile.js
- manifest.json
Hold <kbd>Alt</kbd> and click on a gladiator name to challenge using default tactics.
> [feat] Quick challenge

- js/challenge.js
- js/duelReport.js
- js/profile.js
- Default: redirect to challenge page instead (for custom tactics)
- Alt + click -> challenge with default tactics (for consistency with Quick challenge)
- Hover to see default tactics used
Closes #59
> [feat] Quick challenge: revamp behavior

- manifest.json
New
- [feat] Quick challenge
- [feat] Player status: health status tooltip
- [feat] Persistent filters across page navigation
Changed
- [feat] Quick challenge: revamp behavior
- [fix] Quick buy: prevent layout shift
- [style] Team game: align chat timestamps
> [release] Version 1.9.0

- js/talentCalculator/dwarf.js
- js/talentCalculator/elf.js
- js/talentCalculator/orc.js
- js/talentCalculator/troll.js
Preliminary talent updates for season 8
> [fix] Prepare talent calculator for season 8

- js/attributes.js
- js/edrania.js
- manifest.json
> [feat] Attributes: show damage bonus from strength

- js/duelReport.js
> [feat] Duel report: link gladiator names in footer to profile

- js/edrania.js
- js/tournament.js
- manifest.json
- Prefetch own games
- Lazy load the rest
Closes #89
> [feat] Tournament: link played games to duel report

- js/playerStatus.js
> [fix] Don't init player status if element not present

- js/edrania.js
> [feat] Create gladiator: show derived points from attributes

- js/auction.js
- js/searchGladiator.js
- js/workDistrict.js
- js/workshop.js
- Auction: free search
- Search gladiator: gladiator name
- Work district: time select
- Workshop: work input
Closes #70
> [feat] Auto-focus main inputs

- js/workDistrict.js
- popup.html
> [feat] Work district: duel friendly jobs and default rounds

- js/attributes.js
- js/auction.js
- js/duelReport.js
- js/edrania.js
- js/playerStatus.js
- js/searchGladiator.js
- js/talentCalculator/dwarf.js
- js/talentCalculator/elf.js
- js/talentCalculator/orc.js
- js/talentCalculator/troll.js
- js/tournament.js
- js/workDistrict.js
- js/workshop.js
- manifest.json
- popup.html
**New**
- Work district: duel friendly jobs and default rounds
- Auto-focus main inputs
- Create gladiator: show derived points from attributes
- Tournament: link played games to duel report
- Duel report: link gladiator names in footer to profile
- Attributes: show damage bonus from strength
**Changed**
- Don't init player status if element not present
- Prepare talent calculator for season 8
> [release] Version 1.10.0

- js/workDistrict.js
Incorrect comparison between string and number.
> [fix] Work district: duel friendly jobs is not working

- js/hoverInfo.js
- popup.html
- Rename "Attributes" setting to "My Gladiator"
- Rename "Weapon" setting to "Arsenal"
> [feat] Hover info: arsenal

- css/edrania.css
- js/hoverInfo.js
- js/tournament.js
Overhaul of hover info box.
- Various tournament fixes
- Fix box placement calculations
- Remove more whitespace from equipment info box
- Remove Intelligence header if empty values
- Render dead player content
- Use spinner cursor for tour duel report
> feat] Hover info: avatar

- js/clanMine.js
- js/edrania.js
- manifest.json
- Auto-focus work input
Closes #72
> [feat] Clan mine: default player rounds - 1

- js/clanStockpile.js
- js/edrania.js
- manifest.json
> [feat] Clan stockpile: sort selects alphabetically

- css/edrania.css
- css/popup.css
- js/edrania.js
- js/myClan.js
- js/profile.js
- manifest.json
- popup.html
> [feat] Clan: replace work district with mine

- css/edrania.css
- css/popup.css
- js/attributes.js
- js/clanMine.js
- js/clanStockpile.js
- js/duelReport.js
- js/edrania.js
- js/hoverInfo.js
- js/myClan.js
- js/profile.js
- js/teamGame.js
- js/tournament.js
- manifest.json
- popup.html
**New**
- Clan mine: default player rounds - 1
- Clan mine: auto-focus work input
- Clan stockpile: sort selects alphabetically
- Clan: replace work district with mine
- Auto-focus team game chat and random duel form
**Changed**
- Styled settings popup
**Fixed**
- Adjust estimated damage bonus formula
- Switch order of team max damage and total level
- Duel report: footer link is styled as logo
> [release] Version 1.12.0

- js/talentCalculator.js
- js/talentCalculator/dwarf.js
- js/talentCalculator/elf.js
- js/talentCalculator/human.js
- js/talentCalculator/orc.js
- js/talentCalculator/troll.js
Season IX
- Add new attribute: Unarmed
- Truncate derived points
> [fix] Adjust bonus factors in talent calculator

- js/attributes.js
- js/talentCalculator.js
- js/talentCalculator/dwarf.js
- js/talentCalculator/elf.js
- js/talentCalculator/human.js
- js/talentCalculator/orc.js
- js/talentCalculator/troll.js
- manifest.json
**Fixed**
- Talent calcuator: adjust bonus factors
- Talent calculator: add new attribute "Unarmed"
- Talent calculator: truncate derived points
> [release] Version 1.12.1

- js/myClan.js
Speeds up replacement of work district link.
> [perf] Cache clan mine URL in storage

- js/tavern.js
- js/workDistrict.js
- popup.html
"Silvermynt" (silver coins) is a thing of the past and not really referred to in Edrania.
> [fix] Rename "sm" to "mynt"

- js/duelReport.js
- manifest.json
**Fixes**
- Duel report: rematch button links to training camp for "Armored zebra"
> [release] Version 1.13.1
